# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: appphp8

# The type of the application to build.
type: php:8.1
build:
    flavor: composer

dependencies:
    php:
        "platformsh/client": "2.x-dev"
        composer/composer: '^2'


# The hooks that will be performed when the package is deployed.
hooks:
    build: |
        set -   e
        composer -V
        # invalid command error here to be a build error

    deploy: |
        set -e
        composer -V


# .platform.app.yaml

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
#relationships:
#    database: "db:mysql"

# The size of the persistent disk of the application (in MB).
disk: 1024

# The mounts that will be performed when the package is deployed.
mounts:
    # Because this directory is in the webroot, files here will be web-accessible.
    'web/def':
        source: local
        source_path: uploads123
    # Files in this directory will not be web-accessible.
    'private':
        source: local
        source_path: private
    'src/web/themes/custom/mt':
        source: local
        source_path: ''


# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"
            index:
                - index.php
            expires: -1
            scripts: true
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf|pdf|xml|txt|csv|html?|xls(x|m)?|docx?|pptx?)$':
                    allow: true
            request_buffering:
                enabled: true
                max_request_size: 250m
            headers:
                X-Frame-Options: SAMEORIGIN
